name: testapp
description: A new Flutter project.

dependencies:
  http: '>=0.11.3+12'
  intl: 0.15.2
  video_player: '0.0.7'
  flutter_webview_plugin: '^0.0.9'
  font_awesome_flutter: ^5.0.0
  shared_preferences: '^0.3.0'
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter



# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets: 
    - images/hockey/Ducks.png
    - images/hockey/Canadiens.png
    - images/hockey/Coyotes.png
    - images/hockey/Flames.png
    - images/hockey/Oilers.png
    - images/hockey/Kings.png
    - images/hockey/Canucks.png
    - images/hockey/Blackhawks.png
    - images/hockey/Avalanche.png
    - images/hockey/Stars.png
    - images/hockey/Predators.png
    - images/hockey/Sabres.png
    - images/hockey/Panthers.png
    - images/hockey/Lightning.png
    - images/hockey/Maple Leafs.png
    - images/hockey/Hurricanes.png
    - images/hockey/Blue Jackets.png
    - images/hockey/Devils.png
    - images/hockey/Islanders.png
    - images/hockey/Rangers.png
    - images/hockey/Flyers.png
    - images/hockey/Penguins.png
    - images/hockey/Capitals.png
    - images/hockey/Blues.png
    - images/hockey/Senators.png
    - images/hockey/Bruins.png
    - images/hockey/Red Wings.png
    - images/hockey/Jets.png
    - images/hockey/Sharks.png
    - images/hockey/Wild.png
    - images/person.png
    - json/hockey/teams.json
    - json/football/teams.json
    - json/hockey/rosters/canadiens.json
    - json/hockey/rosters/senators.json
    - images/active/nhl.png
    - images/active/nfl.png
    - images/active/nba.png
    - images/active/mlb.png
    - images/active/mls.png
    - images/active/hockey.png
    - images/active/football.png
    - images/active/basketball.png
    - images/active/soccer.png
    - images/active/baseball.png
    - images/inactive/nhl.png
    - images/inactive/nfl.png
    - images/inactive/nba.png
    - images/inactive/mlb.png
    - images/inactive/mls.png
    - images/inactive/hockey.png
    - images/inactive/football.png
    - images/inactive/basketball.png
    - images/inactive/soccer.png
    - images/inactive/baseball.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
